// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE9ni6Bu40s455iduagILtmSSVWdFsBQ8',
    appId: '1:505915447559:web:c6fa3c88caddd792908da2',
    messagingSenderId: '505915447559',
    projectId: 'wastewise-d451e',
    authDomain: 'wastewise-d451e.firebaseapp.com',
    storageBucket: 'wastewise-d451e.firebasestorage.app',
    measurementId: 'G-YCV3J4NMRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLFXH8XMMP7UqcXArNVPsaPlj28P-o9Dc',
    appId: '1:505915447559:android:1e1511797032554d908da2',
    messagingSenderId: '505915447559',
    projectId: 'wastewise-d451e',
    storageBucket: 'wastewise-d451e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZgvoJusW0zjhA-jqcRWb7exNeBbHYM2E',
    appId: '1:505915447559:ios:be3510cedfd0fd9c908da2',
    messagingSenderId: '505915447559',
    projectId: 'wastewise-d451e',
    storageBucket: 'wastewise-d451e.firebasestorage.app',
    iosBundleId: 'com.example.wasteClassifierFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZgvoJusW0zjhA-jqcRWb7exNeBbHYM2E',
    appId: '1:505915447559:ios:be3510cedfd0fd9c908da2',
    messagingSenderId: '505915447559',
    projectId: 'wastewise-d451e',
    storageBucket: 'wastewise-d451e.firebasestorage.app',
    iosBundleId: 'com.example.wasteClassifierFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE9ni6Bu40s455iduagILtmSSVWdFsBQ8',
    appId: '1:505915447559:web:bcebca68a2ed1f40908da2',
    messagingSenderId: '505915447559',
    projectId: 'wastewise-d451e',
    authDomain: 'wastewise-d451e.firebaseapp.com',
    storageBucket: 'wastewise-d451e.firebasestorage.app',
    measurementId: 'G-J834GVCS88',
  );

}